  
server:
    port: 5000
spring:
    datasource:
      url: jdbc:mysql://localhost:3306/test
      username: root
      password: 
      driver-class-name: com.mysql.jdbc.Driver
mybatis: 
    configuration:
      cache-enabled: false
    type-aliases-package: com.bright.domain
    